version: '1'
services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
